name: example
description: Example for action_slider.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  action_slider:
    path: ..

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2

flutter:

  uses-material-design: true
